### ISSUE TITLE
Saving variant entry data produces error about missing storefront_id due to missing field

### ISSUE THREAD

**Issue by ncla** [jackabox/statamic-shopify#122]
With the current blueprint for variants, if you save the variant (edit title or have some custom additional field), Statamic will remove storefront_id property from variant content file, because there is no `storefront_id` field in the blueprint. And if you are using the `product_variants` tag in front-end, then there will be exception generating the `<select>` because the tag uses that property.

![image](https://user-images.githubusercontent.com/5507083/180007621-4a9ce427-1e13-45c1-878d-234cb3b0d4e7.png)

As a workaround, adding storefront_id field to the variant blueprint will prevent from this happening.

```yaml
      -
        handle: storefront_id
        field:
          type: hidden
          listable: hidden
          antlers: false
          display: 'Storefront ID'

```
